name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build ${{ matrix.target.rid }}
    runs-on: ${{ matrix.target.os }}

    strategy:
      fail-fast: false
      matrix:
        target:
          - rid: win-x64
            os: windows-latest
            archive_name: McHoneypot-win-x64.zip

          - rid: linux-x64
            os: ubuntu-latest
            archive_name: McHoneypot-linux-x64.tar.gz

          - rid: linux-arm64
            os: ubuntu-latest
            archive_name: McHoneypot-linux-arm64.tar.gz

          - rid: osx-x64 # macOS Intel (amd64)
            os: macos-latest
            archive_name: McHoneypot-osx-x64.tar.gz

          - rid: osx-arm64 # macOS Apple Silicon (M1/M2/M3)
            os: macos-latest
            archive_name: McHoneypot-osx-arm64.tar.gz

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'

      - name: Build / Publish project
        run: dotnet publish McHoneypot.Infrastructure/McHoneypot.Infrastructure.csproj -c Release -r ${{ matrix.target.rid }} -o ./publish

      - name: Compress for Windows
        if: matrix.target.os == 'windows-latest'
        shell: pwsh
        run: Compress-Archive -Path ./publish/* -DestinationPath ./${{ matrix.target.archive_name }}

      - name: Compress for Linux/macOS
        if: matrix.target.os != 'windows-latest'
        run: |
          tar -czvf "${{ matrix.target.archive_name }}" -C ./publish .

      - name: Rename output artifact
        shell: bash
        run: |
          cd ./publish

          if [ "${{ matrix.target.os }}" = "windows-latest" ]; then
            mv McHoneypot.Infrastructure.exe ${{ matrix.target.artifact_name }}
          else
            mv McHoneypot.Infrastructure ${{ matrix.target.artifact_name }}
          fi

      - name: Upload artifacts to Release
        uses: softprops/action-gh-release@v3
        with:
          files: ./publish/${{ matrix.target.artifact_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}